# syntax=docker/dockerfile:1

FROM node:24-bookworm-slim AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS dependencies
ENV HUSKY=0
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SITE_API_BASE_URL=https://api2.jacochef.ru/site/public/index.php/
ARG NEXT_PUBLIC_CAFE_REVIEW_API_URL=https://api2.jacochef.ru/site/public/index.php/cafe_review
ARG NEXT_PUBLIC_RECOMMENDATIONS_ENABLED=false
ARG NEXT_PUBLIC_SENTRY_CUSTOM_MONITORING_ENABLED=false
ARG NEXT_PUBLIC_SENTRY_DSN=
ARG NEXT_PUBLIC_VK_IMG=https://mainimg.jacofood.ru/
ARG NEXT_PUBLIC_YANDEX_IMG=https://mainimg.jacofood.ru/
ARG NEXT_PUBLIC_YANDEX_STORAGE=https://topimg.jacofood.ru/
ARG NEXT_PUBLIC_YANDEX_TOKEN_FIREBASE=
ARG NEXT_PUBLIC_YANDEX_TOKEN_MAP=
ARG NEXT_PUBLIC_YANDEX_TOKEN_SUGGEST=

ENV NEXT_PUBLIC_SITE_API_BASE_URL=$NEXT_PUBLIC_SITE_API_BASE_URL
ENV NEXT_PUBLIC_CAFE_REVIEW_API_URL=$NEXT_PUBLIC_CAFE_REVIEW_API_URL
ENV NEXT_PUBLIC_RECOMMENDATIONS_ENABLED=$NEXT_PUBLIC_RECOMMENDATIONS_ENABLED
ENV NEXT_PUBLIC_SENTRY_CUSTOM_MONITORING_ENABLED=$NEXT_PUBLIC_SENTRY_CUSTOM_MONITORING_ENABLED
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_VK_IMG=$NEXT_PUBLIC_VK_IMG
ENV NEXT_PUBLIC_YANDEX_IMG=$NEXT_PUBLIC_YANDEX_IMG
ENV NEXT_PUBLIC_YANDEX_STORAGE=$NEXT_PUBLIC_YANDEX_STORAGE
ENV NEXT_PUBLIC_YANDEX_TOKEN_FIREBASE=$NEXT_PUBLIC_YANDEX_TOKEN_FIREBASE
ENV NEXT_PUBLIC_YANDEX_TOKEN_MAP=$NEXT_PUBLIC_YANDEX_TOKEN_MAP
ENV NEXT_PUBLIC_YANDEX_TOKEN_SUGGEST=$NEXT_PUBLIC_YANDEX_TOKEN_SUGGEST

RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

RUN groupadd --system --gid 1001 nodejs \
    && useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
